[package]
name = "chem_format_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc_parser = { git = "https://github.com/LipidL/arc_parser.git" }
regex = "1.10.2"
clap = "4.4.8"